# Generated by Django 4.0 on 2022-01-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='numberOfInteractions',
            field=models.IntegerField(default=0),
        ),
    ]
