# Generated by Django 3.1.3 on 2022-01-06 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userbook', '0002_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
