# Generated by Django 3.1.3 on 2022-01-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userbook', '0003_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bookuser',
            unique_together={('userid', 'bookid')},
        ),
    ]
